INSERT INTO monumento (codigo_pais, nombre_pais, nombre_ciudad, latitud, longitud, localizacion, nombre_monumento, descripcion_monumento, foto_url) VALUES ('ES', 'España', 'Madrid', 40.4168, -3.7038, 'Plaza de Cibeles', 'Palacio de Cibeles', 'Emblemático edificio de principios del siglo XX, sede del Ayuntamiento de Madrid', 'https://example.com/cibeles.jpg');
INSERT INTO monumento (codigo_pais, nombre_pais, nombre_ciudad, latitud, longitud, localizacion, nombre_monumento, descripcion_monumento, foto_url) VALUES ('FR', 'Francia', 'París', 48.8584, 2.2945, 'Champ de Mars', 'Torre Eiffel', 'Icónica torre de hierro construida en 1889, símbolo de París y Francia', 'https://example.com/torre-eiffel.jpg');
INSERT INTO monumento (codigo_pais, nombre_pais, nombre_ciudad, latitud, longitud, localizacion, nombre_monumento, descripcion_monumento, foto_url) VALUES ('IT', 'Italia', 'Roma', 41.8902, 12.4922, 'Piazza del Colosseo', 'Coliseo Romano', 'Anfiteatro antiguo construido en el siglo I d.C., una de las siete maravillas del mundo moderno', 'https://example.com/coliseo.jpg');
INSERT INTO monumento (codigo_pais, nombre_pais, nombre_ciudad, latitud, longitud, localizacion, nombre_monumento, descripcion_monumento, foto_url) VALUES ('ES', 'España', 'Barcelona', 41.4036, 2.1744, 'Carrer de Mallorca', 'Sagrada Familia', 'Basílica diseñada por Antoni Gaudí, obra maestra del modernismo catalán', 'https://example.com/sagrada-familia.jpg');
INSERT INTO monumento (codigo_pais, nombre_pais, nombre_ciudad, latitud, longitud, localizacion, nombre_monumento, descripcion_monumento, foto_url) VALUES ('GB', 'Reino Unido', 'Londres', 51.5007, -0.1246, 'Westminster', 'Big Ben', 'Famosa torre del reloj del Palacio de Westminster, símbolo de Londres', 'https://example.com/big-ben.jpg');
INSERT INTO monumento (codigo_pais, nombre_pais, nombre_ciudad, latitud, longitud, localizacion, nombre_monumento, descripcion_monumento, foto_url) VALUES ('US', 'Estados Unidos', 'Nueva York', 40.6892, -74.0445, 'Liberty Island', 'Estatua de la Libertad', 'Monumento neoclásico regalado por Francia en 1886, símbolo de libertad', 'https://example.com/estatua-libertad.jpg');
INSERT INTO monumento (codigo_pais, nombre_pais, nombre_ciudad, latitud, longitud, localizacion, nombre_monumento, descripcion_monumento, foto_url) VALUES ('EG', 'Egipto', 'Giza', 29.9792, 31.1342, 'Necrópolis de Giza', 'Pirámides de Giza', 'Antiguas tumbas faraónicas construidas hace más de 4500 años', 'https://example.com/piramides.jpg');
INSERT INTO monumento (codigo_pais, nombre_pais, nombre_ciudad, latitud, longitud, localizacion, nombre_monumento, descripcion_monumento, foto_url) VALUES ('IN', 'India', 'Agra', 27.1751, 78.0421, 'Agra', 'Taj Mahal', 'Mausoleo de mármol blanco construido en el siglo XVII, símbolo del amor eterno', 'https://example.com/taj-mahal.jpg');

